### ISSUE TITLE
pwsh error executing remote invoke-atomictest from linux to windows

### ISSUE THREAD

**Issue by Guillaume-Muller** [redcanaryco/invoke-atomicredteam#73] opened 2021-09-08 10:34 UTC
When I try to run a powershell test from Debian to Windows, I get the following error 

**_Usage: pwsh[.exe] 
(...)
The argument "&" is not recognized as the name of a script file..._**

It is working well when I run a "command-prompt" test

It seems that pwsh is expecting a file name instead of a command line. I tried "-c" before the powershell command but not working

**Comment by R3dP1ll** [comment] 2021-11-15 19:50
Duplicate of #77 I guess?

**Comment by clr2of8** [comment] 2022-03-15 22:40
This works for me from Ubuntu to Windows 10. I'll close this out for now but if you have the issue again you can reopen and include a screenshot of the specific test failing so I can check. thx

![image](https://user-images.githubusercontent.com/22311332/158484105-0df8712f-e443-404d-a116-ddfd5b4f1cea.png)

**Closed by clr2of8** 2022-03-15 22:40 UTC
